---
# handlers file for monitor_service

- name: Restart prometheus
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: prometheus

- name: Reload haproxy
  ansible.builtin.systemd_service:
    state: reloaded
    name: haproxy
