---
# handlers file for vpn_service
- name: netfilter-persistent-save
  ansible.builtin.command: service netfilter-persistent save
  listen: netfilter-persistent-save

- name: openvpn-restart
  service:
   name: openvpn@server
   state: restarted
  listen: openvpn-restart

- name: Restart haproxy
  ansible.builtin.service:
    daemon_reload: true
    name: haproxy
    state: restarted

- name: Reload haproxy
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: reloaded
    name: haproxy

- name: Restart prometheus
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: prometheus

- name: Restart alertmanager
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: alertmanager
