frontend http-prometheus
	bind *:80
	mode http
	acl lets_encrypt path_beg /.well-known/acme-challenge/
	acl goto-prometheus-http hdr(host) -i prometheus.techenergoanalit.ru

	# Use wanted backend, based on ACL 
	use_backend prometheus-http-LE if lets_encrypt goto-prometheus-http

frontend https-prometheus
	bind *:443
	mode tcp
	option tcplog
	tcp-request inspect-delay 5s
	tcp-request content accept if { req_ssl_hello_type 1 }
	use_backend prometheus-https if { req.ssl_sni -i prometheus.techenergoanalit.ru }

backend prometheus-http-LE
	mode http
	balance roundrobin
	server server1 monitor.techenergoanalit.ru:80

backend prometheus-https
	mode tcp
	balance roundrobin
	option ssl-hello-chk
	server server1 monitor.techenergoanalit.ru:443
