---
# tasks file for monitor_service

- name: Config https and auth
  ansible.builtin.include_tasks: file=prometheus_server_certbot.yml
  tags:
    - always 

- name: Setup prometheus server
  ansible.builtin.include_tasks: file=prometheus_server_setup.yml
  tags:
    - always 

- name: Setup https and proxy prometheus server
  ansible.builtin.include_tasks: file=prometheus_server_setup_https_and_proxy.yml
  tags:
    - always 
