- name: Install snapd pkg
  ansible.builtin.apt: name={{ package_list }}
  vars:
    package_list: ['snapd']
  when: inventory_hostname == "monitor.techenergoanalit.ru"

- name: Install "certbot" 
  community.general.snap:
    name: certbot
    classic: true
  when: inventory_hostname == "monitor.techenergoanalit.ru"

- name: Create a symbolic link for certbot bin
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
  when: inventory_hostname == "monitor.techenergoanalit.ru"

- name: Create a keys directory if it does not exist
  ansible.builtin.file:
    path: /etc/prometheus/keys/
    state: directory
    mode: '0755'
  when: inventory_hostname == "monitor.techenergoanalit.ru"

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: deploy_script.sh
    dest: /etc/letsencrypt/renewal-hooks/deploy/
    mode: '0755'
  when: inventory_hostname == "monitor.techenergoanalit.ru"

- name: Get ssl cert
  ansible.builtin.command:
    argv:
      - certbot
      - certonly
      - --force-renewal
      - --standalone
      - --register-unsafely-without-email
      - --agree-tos
      - --domains
      - prometheus.techenergoanalit.ru
  args:
    creates: /etc/letsencrypt/live/prometheus.techenergoanalit.ru/fullchain.pem
  when: inventory_hostname == "monitor.techenergoanalit.ru"
  notify: 
    - Restart prometheus
