- name: Install acl pkg
  ansible.builtin.apt: name={{ package_list }}
  vars:
    package_list: ['acl']
  when: inventory_hostname in groups["monservers"]

- name: Prometheus user create
  ansible.builtin.user: name={{ prometheus_user }} shell=/usr/bin/false create_home=false comment="non root user for prometheus"
  when: inventory_hostname == "monitor.techenergoanalit.ru"

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/etc/prometheus" 
    - "/var/lib/prometheus"
    - "/var/distr/prometheus"
  when: inventory_hostname == "monitor.techenergoanalit.ru"

- name: Change ownership of a directory for prometheus
  ansible.builtin.file:
    path: /var/lib/prometheus
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
  when: inventory_hostname == "monitor.techenergoanalit.ru"

- name: Download prometheus
  ansible.builtin.get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.49.1/prometheus-2.49.1.linux-amd64.tar.gz
    dest: /var/distr/prometheus
  when: inventory_hostname == "monitor.techenergoanalit.ru"

- name: Extract prometheus
  ansible.builtin.unarchive:
    remote_src: true
    src: /var/distr/prometheus/prometheus-2.49.1.linux-amd64.tar.gz
    dest: /var/distr/prometheus
  when: inventory_hostname == "monitor.techenergoanalit.ru"

- name: Copy prometheus bin files
  ansible.builtin.copy:
    remote_src: true
    src: "{{ item }}"
    dest: /usr/local/bin
    mode: u=rw,g=r,o=rx
  loop:
    - "/var/distr/prometheus/prometheus-2.49.1.linux-amd64/prometheus"
    - "/var/distr/prometheus/prometheus-2.49.1.linux-amd64/promtool"
  when: inventory_hostname == "monitor.techenergoanalit.ru"
  notify:
    - Restart prometheus

- name: Copy prometheus files
  ansible.builtin.copy:
    remote_src: true
    src: "{{ item }}"
    dest: /etc/prometheus/
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
  loop:
    - "/var/distr/prometheus/prometheus-2.49.1.linux-amd64/consoles"
    - "/var/distr/prometheus/prometheus-2.49.1.linux-amd64/console_libraries"
  when: inventory_hostname == "monitor.techenergoanalit.ru"
  notify:
    - Restart prometheus

- name: Copy prometheus main cfg
  ansible.builtin.template:
    src: templates/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  when: inventory_hostname == "monitor.techenergoanalit.ru"
  notify:
    - Restart prometheus

- name: Copy prometheus web cfg
  ansible.builtin.template:
    src: templates/web-config.yml.j2
    dest: /etc/prometheus/web-config.yml
  when: inventory_hostname == "monitor.techenergoanalit.ru"
  notify:
    - Restart prometheus

- name: Copy prometheus systemd service
  ansible.builtin.template:
    src: templates/prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  when: inventory_hostname == "monitor.techenergoanalit.ru"
  notify:
    - Restart prometheus

