---
# tasks file for haproxy_setup

- name: Add haproxy stable repository from PPA and install its signing key on Ubuntu target
  ansible.builtin.apt_repository:
    repo: ppa:vbernat/haproxy-2.9
  when: inventory_hostname == "ovpn-srv.techenergoanalit.ru"

- name: Install haproxy pkg
  ansible.builtin.apt: name={{ package_list }}
  vars:
    package_list: ['haproxy=2.9.*']
  when: inventory_hostname == "ovpn-srv.techenergoanalit.ru"

- name: Create a haproxy cfg directory if it does not exist
  ansible.builtin.file:
    path: /etc/haproxy/conf.d
    state: directory
  when: inventory_hostname == "ovpn-srv.techenergoanalit.ru"

- name: Copy haproxy default file
  ansible.builtin.copy:
    src: haproxy
    dest: /etc/default/
  when: inventory_hostname == "ovpn-srv.techenergoanalit.ru"
  notify:
    - Restart haproxy

- name: Copy haproxy cfg
  ansible.builtin.copy:
    src: haproxy.cfg
    dest: /etc/haproxy/
  when: inventory_hostname == "ovpn-srv.techenergoanalit.ru"
  notify:
    - Restart haproxy
